Traceback (most recent call last):
  File "/home/kodyatemirov/face-verification/app/main_arcface.py", line 29, in <module>
    logging.FileHandler('/app/logs/arcface.log')
  File "/usr/lib/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/logs/arcface.log'
